wireguard.postinst now reloads the module if possible (Closes: #913446)
With these changes, i've kept the bulk of Fabian's work, but i'm
trying to handle the corner cases differently.

In particular:

 * pass wg-quick unit names in one pass to systemctl, rather than
   stepping through them.

 * avoid magic sleep time (3 seconds) -- if "systemctl stop" doesn't
   wait properly, that's a bug in systemctl, and we should report it
   there.

 * use dpkg --compare-versions to see whether the module is being
   upgraded.

 * treat failure to rmmod the same as if a non-wg-quick interface is
   present on the system.

 * gracefully handle scenarios where the module was not already
   loaded, or failed to build for the current kernel.

 * "systemctl daemon-reload" happens before the first interaction with
   systemd.

diff --git a/debian/wireguard.postinst b/debian/wireguard.postinst
--- a/debian/wireguard.postinst
+++ b/debian/wireguard.postinst
@@ -1,53 +1,53 @@
 #!/bin/sh
 set -e
 
-#DEBHELPER#
-
 case "$1" in
-	install)
-		;;
+    install)
+    ;;
+    
+    configure|reconfigure)
+	# Nothing to do if the wireguard module is not already loaded.
+	if [ ! -f "/sys/module/wireguard/version" ]; then
+	    exit 0
+	fi
 
-	configure|reconfigure)
-		# Check if the wireguard module is loaded else the install will fail.
-		if [ ! -f "/sys/module/wireguard/version" ]; then
-			exit 0
+        # Get the version of the current loaded module:
+	old_version="$(cat /sys/module/wireguard/version)"
+        # Get the version of the latest available module:
+	if ! new_version="$(modinfo -F version wireguard 2>/dev/null)"; then 
+            exit 0
+        fi
+
+	if dpkg --compare-versions "$old_version" lt "$new_version"; then
+	    if [ -d /run/systemd/system ]; then
+		systemctl daemon-reload || true
+		units="$(systemctl list-units --state=active --plain --no-legend 'wg-quick@*.service' | awk '{print $1}')"
+		if [ -n "$units" ]; then
+		    echo "Stopping currently active wg-quick@ unit instances..." >&2
+                    systemctl stop $units || true
 		fi
-
-		old_version="$(cat /sys/module/wireguard/version)" # Get the version of the current loaded module
-		new_version="$(modinfo -F version wireguard 2>/dev/null)" # Get the version of the latest available module
-
-		if ! [ "$old_version" = "$new_version" ]; then
-			if [ -d /run/systemd/system ]; then
-				units="$(systemctl list-units --state=active --plain --no-legend 'wg-quick@*.service' 2>/dev/null|cut -d' ' -f1)"
-				if [ -n "$units" ]; then
-					echo "Stopping currently active wg-quick@ unit instances.." >&2
-					for unit in $units; do
-						echo "$unit" >&2
-						systemctl stop "$unit" >/dev/null || true
-					done
-					echo "Sleeping 3 seconds..." >&2
-					sleep 3
-				fi
-			fi
-			if [ -n "$(wg show interfaces)" ]; then
-				echo "Warning: Wireguard interfaces currently configured, not reloading module" >&2
-			else
-				echo "Reloading wireguard module..." >&2
-				rmmod wireguard
-				modprobe wireguard
-			fi
-			if [ -d /run/systemd/system ]; then
-				systemctl daemon-reload >/dev/null || true
-				if [ -n "$units" ]; then
-					echo "Starting previously active wg-quick@ unit instances.." >&2
-					for unit in $units; do
-						echo "$unit" >&2
-						systemctl start "$unit" >/dev/null || true
-					done
-				fi
-			fi
+            fi
+	    if [ -n "$(wg show interfaces)" ]; then
+		echo "Warning: Wireguard interfaces currently configured, not reloading module" >&2
+	    else
+		echo "Reloading wireguard module..." >&2
+		if ! rmmod wireguard ; then
+		    echo "Warning: failed to unload wireguard module" >&2
+                else
+		    modprobe wireguard
+                fi
+	    fi
+	    if [ -d /run/systemd/system ]; then
+		if [ -n "$units" ]; then
+		    echo "Starting previously active wg-quick@ unit instances..." >&2
+                    systemctl start $units || true
 		fi
-		;;
-	*)
-		;;
+	    fi
+        fi
+	;;
+    *)
+	;;
 esac
+
+#DEBHELPER#
+exit 0
