cleanup whitespace

diff --git a/debian/wireguard-dkms.postinst b/debian/wireguard-dkms.postinst
--- a/debian/wireguard-dkms.postinst
+++ b/debian/wireguard-dkms.postinst
@@ -4,69 +4,69 @@ set -e
 #DEBHELPER#
 
 reboot_required() {
-        # trigger an update notification that recommends a reboot
-        # (used by unattended-upgrades etc.)
-        touch /run/reboot-required || true
+    # trigger an update notification that recommends a reboot
+    # (used by unattended-upgrades etc.)
+    touch /run/reboot-required || true
 
-        if ! grep -Fqsx wireguard-dkms /run/reboot-required.pkgs; then
-            echo wireguard-dkms >> /run/reboot-required.pkgs || true
-        fi
+    if ! grep -Fqsx wireguard-dkms /run/reboot-required.pkgs; then
+        echo wireguard-dkms >> /run/reboot-required.pkgs || true
+    fi
 }
 
 case "$1" in
     install)
     ;;
-    
-    configure|reconfigure)
-	# Nothing to do if the wireguard module is not already loaded.
-	if [ ! -f "/sys/module/wireguard/version" ]; then
-	    exit 0
-	fi
 
-        # Get the version of the current loaded module:
-	old_version="$(cat /sys/module/wireguard/version)"
-        # Get the version of the latest available module:
-	if ! new_version="$(modinfo -F version wireguard 2>/dev/null)"; then 
+    configure|reconfigure)
+        # Nothing to do if the wireguard module is not already loaded.
+        if [ ! -f "/sys/module/wireguard/version" ]; then
             exit 0
         fi
 
-	if dpkg --compare-versions "$old_version" lt "$new_version"; then
+        # Get the version of the current loaded module:
+        old_version="$(cat /sys/module/wireguard/version)"
+        # Get the version of the latest available module:
+        if ! new_version="$(modinfo -F version wireguard 2>/dev/null)"; then
+            exit 0
+        fi
+
+        if dpkg --compare-versions "$old_version" lt "$new_version"; then
             # Do nothing if the "wireguard" package is not on the system.
             if ! dpkg --status wireguard >/dev/null 2>/dev/null; then
                 reboot_required
                 exit 0
             fi
 
-	    if [ -d /run/systemd/system ]; then
-		systemctl daemon-reload || true
-		units="$(systemctl list-units --state=active --plain --no-legend 'wg-quick@*.service' | awk '{print $1}')"
-		if [ -n "$units" ]; then
-		    echo "Stopping currently active wg-quick@ unit instances..." >&2
+            if [ -d /run/systemd/system ]; then
+                systemctl daemon-reload || true
+                units="$(systemctl list-units --state=active --plain --no-legend 'wg-quick@*.service' | awk '{print $1}')"
+                if [ -n "$units" ]; then
+                    echo "Stopping currently active wg-quick@ unit instances..." >&2
                     systemctl stop $units || true
-		fi
-            fi
-	    if [ -n "$(wg show interfaces)" ]; then
-		reboot_required
-		echo "Warning: Wireguard interfaces currently configured, not reloading module" >&2
-	    else
-		echo "Reloading wireguard module..." >&2
-		if ! rmmod wireguard ; then
-		    reboot_required
-		    echo "Warning: failed to unload wireguard module" >&2
-                else
-		    modprobe wireguard
                 fi
-	    fi
-	    if [ -d /run/systemd/system ]; then
-		if [ -n "$units" ]; then
-		    echo "Starting previously active wg-quick@ unit instances..." >&2
+            fi
+            if [ -n "$(wg show interfaces)" ]; then
+                reboot_required
+                echo "Warning: Wireguard interfaces currently configured, not reloading module" >&2
+            else
+                echo "Reloading wireguard module..." >&2
+                if ! rmmod wireguard ; then
+                    reboot_required
+                    echo "Warning: failed to unload wireguard module" >&2
+                else
+                    modprobe wireguard
+                fi
+            fi
+            if [ -d /run/systemd/system ]; then
+                if [ -n "$units" ]; then
+                    echo "Starting previously active wg-quick@ unit instances..." >&2
                     systemctl start $units || true
-		fi
-	    fi
+                fi
+            fi
         fi
-	;;
+        ;;
     *)
-	;;
+        ;;
 esac
 
 exit 0
